apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
  labels:
    app: flask-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      securityContext:  # Pod-level security
        runAsNonRoot: true
      containers:
      - name: flask-app
        image: sameer2699/flask-hello-world:latest
        securityContext:  # Container-level security
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000  # Specific non-root user ID
          runAsGroup: 3000
          readOnlyRootFilesystem: true  # Additional hardening
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5