apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
  namespace: flask-hello-world-namespace  # Custom namespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      securityContext:
        runAsUser: 1001  # High UID to avoid conflicts
        seccompProfile:
          type: RuntimeDefault  # Set seccomp profile
      containers:
        - name: flask-hello-world
          image: flask-hello-world@sha256:<digest>  # Use digest instead of tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: my-volume
              mountPath: /my-data
      serviceAccountName: flask-hello-world-sa
---
apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world
  namespace: flask-hello-world-namespace  # Custom namespace
spec:
  type: NodePort
  selector:
    app: flask-hello-world
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flask-hello-world-network-policy
  namespace: flask-hello-world-namespace
spec:
  podSelector:
    matchLabels:
      app: flask-hello-world
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: flask-hello-world
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: flask-hello-world
